# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04cfd77d51adf2e7290460689a94dbf4b9f5b36e08e5779b7170d59bd789aa87663610686c226d5f5b4fbf88e534157aab4aaa80b3939beb3e0b8931b7e6731f

test:
  secret_key_base: a99ffcef0cbbf98b415bba768518df384e94e5cff07b5d757299952bee7d4a810064e6235d681e814481babed8774bb883ed78b8719de0812b813935ea43a5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
